server:
  port: 8081
  servlet:
    context-path: /ssk
#  ssl:
#    key-store: classpath:javaboy.p12
#    key-alias: tomcathttps
#    key-store-password: admin123456

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ssk.mapper

#showSql
logging:
  level:
    com:
      ssk:
        mapper : debug
